### ISSUE TITLE
upload my configuration

### ISSUE THREAD

**Issue by zwb124** [Toxblh/MTMR-presets#32]
Sorry, I don't quite use github, I want to upload my configuration, but I don't know where it's passed and it doesn't seem to have created a folder

**Comment by Toxblh** [comment]
Don’t worry you can upload it to the thread, I add it self

**Comment by zwb124** [comment]
thanks
[zwb124.zip](https://github.com/Toxblh/MTMR-presets/files/4311089/zwb124.zip)
