### ISSUE TITLE
MetaSean Preset not working

### ISSUE THREAD

**Issue by Lord-V15** [Toxblh/MTMR-presets#43]
I cloned the latest version of the MTMR-presets and everything else is working fine but unfortunately the preset called "metasean" is not working as my Touch Bar shows a "bad preset" icon only.

**Comment by Highwall2016** [comment]
I modify it(add \\ before the space), and it works.

`  {
    "type": "shellScriptTitledButton",
    "source": {
      "inline": "echo $(sh ~/Library/Application\\ Support/MTMR/randomQuotes.sh)"
    },
    "width": 588,
    "refreshInterval": 60, // in seconds
    "align": "left",
    "bordered": false
  },`
