### ISSUE TITLE
Weather not working

### ISSUE THREAD

**Issue by Ashvir16** [Toxblh/MTMR-presets#91]
{ "type": "weather",
"refreshInterval": 60,
"units": "imperial",
"align": "right",
"bordered": true,
"icon_type": "images",
"api_key": "bb63967e9be6bb508344d0cd4b57a6e9"},

https://preview.redd.it/4fmwz6xkgo771.png?width=2008&format=png&auto=webp&s=79cc0d46d902fec0365e52e125819353a78d17b0

Weather should be on right, but instead an hourglass. Was working at first but stopped and never changed even if I redid it entirely.

**Comment by sonyminer** [comment]
Is the Api_key active/correct? Also, could be that the refreshInterval is too short? Try with 600 and see if it works.

**Comment by sonyminer** [comment]
This is the one I use with a trigger to a weather service (you can change it to your city and other weather service). I replaced my api with yours:

{"type": "weather", "align": "right",  "bordered": true, "refreshInterval": 600, "units": "metric", "icon_type": "images", "api_key": "bb63967e9be6bb508344d0cd4b57a6e9","actions": [ {"trigger": "singleTap", "action":  "openUrl", "url": "https://openweathermap.org/city/3117667"}]},

Let know if it works...

**Comment by Ashvir16** [comment]
> This is the one I use with a trigger to a weather service (you can change it to your city and other weather service). I replaced my api with yours:
> 
> {"type": "weather", "align": "right", "bordered": true, "refreshInterval": 600, "units": "metric", "icon_type": "images", "api_key": "bb63967e9be6bb508344d0cd4b57a6e9","actions": [ {"trigger": "singleTap", "action": "openUrl", "url": "https://openweathermap.org/city/3117667"}]},
> 
> Let know if it works...

It works now! Tysm!
